### ISSUE TITLE
Searching multiple collections

### ISSUE THREAD

**Issue by zaklampert** [meteorhacks/search-source#13]
Hello! This is fantastic.

Is it possible to search multiple collections in one search?

Thank you!

**Comment by arunoda** [comment]
Yes. it is. It's upto you to define the search definition, either on [server](https://github.com/meteorhacks/search-source#define-the-data-source-on-the-server) or [client](https://github.com/meteorhacks/search-source#defining-data-source-in-the-client)

**Comment by zaklampert** [comment]
Should it be as simple as 

'return [Recipes.find(selector, options).fetch(), Products.find(selector, options).fetch() ]'

because that's spitting out a "Modifier must be an object" error.

**Comment by zaklampert** [comment]
Splitting the queries out like this worked.

```javascript
 var recipeFind = Recipes.find(selector, options).fetch()
 var productFind = Products.find(selector, options).fetch()
    
  return  recipeFind, productFind
```

So cool.

**Comment by zaklampert** [comment]
Just kidding. It's actually just searching the second query.

**Comment by zaklampert** [comment]
simply _.extend-ing the two objects worked. like a charm
```javascript
 var recipeFind = Recipes.find(selector, options).fetch()
    var productFind = Products.find(selector, options).fetch()
    var bothFind = _.extend(recipeFind, productFind)
    
   	return {
   		data: bothFind
   	}
```

hooray!
