### ISSUE TITLE
how to search on multiple collection?

### ISSUE THREAD

**Issue by achtan** [meteorhacks/search-source#32]
Hi, how to search on multiple collection at same time?

**Comment by arunoda** [comment]
You can define the source and search from both. Then merge those two results. (two arrays) and return.

**Comment by achtan** [comment]
i but what about client side search?

**Comment by arunoda** [comment]
Okay. I got it. SearchSource does not have a notion about collections. It gets a datastream and it do the search in the client. So, you need to add common field (may be generated a field) to search.

**Comment by arunoda** [comment]
Did you try that?

**Comment by achtan** [comment]
yes i did, for now i have the same field name in each collection, so thats works

**Comment by arunoda** [comment]
Okay. great.
