### ISSUE TITLE
Link to meteorhacks article not working in the docs

### ISSUE THREAD

**Issue by derwaldgeist** [meteorhacks/search-source#51]
I only get an error message that a secure connection cannot be established.

**Comment by WitaliB** [comment]
for me the link is woking. I am using chrome 47

**Comment by derwaldgeist** [comment]
Yes, it's working now for me as well, so I am closing this.

**Comment by kdekooter** [comment]
The link is not working anymore https://meteorhacks.com/implementing-an-instant-search-solution-with-meteor.html. Maybe the content of the article should be included in the docs of this repo?
