### ISSUE TITLE
Only getting results for every second character

### ISSUE THREAD

**Issue by cromosom** [meteorhacks/search-source#7]
I'm getting search-results just every second character I type. It seems to be a problem with rendering because on the server I get results on every character.

**Comment by arunoda** [comment]
How do you call .search method. Are you using something like _.debounce ?
If so, try to change some parameters in it.

**Comment by cromosom** [comment]
"keyup #search-box": _.throttle(function(e) {
      var text = $(e.target).val().trim();
      if (text != currentSearchVal) {
        PackageSearch.search(text);
        currentSearchVal = text;
        console.log(currentSearchVal);
      }
      
    }, 500)

**Comment by arunoda** [comment]
That's the thing. Try to remove throttle and try.
You be you need to tune the timeout delay.

**Comment by cromosom** [comment]
removed but it didn't help. I noticed if I console.log my results helper it logs sometimes two arrays of results and just the second one gets displayed. 

```javascript
  Template.searchResult.helpers({
    results: function() {
      console.log(PackageSearch.getData())
      return PackageSearch.getData();
    },
    isLoading: function() {
      return PackageSearch.getStatus().loading;
    }
  });
```

**Comment by chip** [comment]
I'm having the same issue, even after removing the throttle. After debugging the source, it appears  that it might have something to do with [line 109 in client.js](https://github.com/meteorhacks/search-source/blob/master/lib/client.js#L109).  Anytime `this.getStatus().loading` returns `true`, documents are returned. When it returns `false`, I don't receive any data.

**Comment by arunoda** [comment]
Okay. let me see.

**Comment by chip** [comment]
Great! Thank you. I'm not sure if this is the issue, but the `status` is a **ReactiveVar** that contains a `loaded` key, which sometimes is a `Boolean` value and other times is a `Date`.

**Comment by chip** [comment]
After debugging a bit further, it appears that [this.store.find(selector)](https://github.com/meteorhacks/search-source/blob/master/lib/client.js#L131) returns no data for every even numbered character. Additionally, I've commented out the options for `sort, limit, & transform` to see if that changes anything, but still no data.  I'm at a loss for how to debug this further.

**Comment by arunoda** [comment]
May be, data is getting removed by this:
https://github.com/meteorhacks/search-source/blob/master/lib/client.js#L84

**Comment by chip** [comment]
Thanks for the info. I looked at that code earlier today, but didn't find anything unusual. I'll review it again though tomorrow after I rest.

**Comment by arunoda** [comment]
Thanks for looking on this.

**Comment by ayng** [comment]
I ran into the same issue. If it helps, I found that the search correctly returns matching elements in the collection _excluding_ the elements that were previously returned. If the element showed up in the previous search() call, it will not show up in the next search() call.
